### ISSUE TITLE
Etcher will not allow the drive choice

### ISSUE THREAD

**Issue by rleezim** [resin-io-modules/etcher-latest-version#1]
I've tried with different versions, but each time I run Etcher choose an Image, but when I click on choose drive nothing happens.n hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgghhhhhhhhhhbtbbbbbbbbbbbhhhnnhyyh7hnhyn hy6n 66               6                             6                                                                         yhn 666h This last time I entered: wget https://resin-production-downloads.s3.amazonaws.com/etcher/1.0.0-beta.18/Etcher-1.0.0-beta.18-linux-x64.zip
Then I extract the zip file leaving the AppImage which I enter cd Downloads. Then enter chmod a+x Etcher-linux-x64.AppImage. And finally, sudo ./Etcher-linux-x64.AppImage and click yes to the yes or no prompt. What am I missing. Please help.

**Comment by lurch** [comment]
Can you please report this at https://github.com/resin-io/etcher/issues instead? Thank you.
